// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const isValidUrl = (url: any) => typeof url === 'string' && url.startsWith('http');
const isValidKey = (key: any) => typeof key === 'string' && key.length > 20 && key !== 'undefined';

const SUPABASE_URL = isValidUrl(import.meta.env.VITE_SUPABASE_URL) 
  ? import.meta.env.VITE_SUPABASE_URL 
  : "https://unoixnntunmnoeeqfhqq.supabase.co";

const SUPABASE_PUBLISHABLE_KEY = isValidKey(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY) 
  ? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY 
  : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVub2l4bm50dW5tbm9lZXFmaHFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1MTIxNzQsImV4cCI6MjA5MzA4ODE3NH0.rEHAx5YAuKKsQnL8LXF7QkbcpxHO6kWkQpujJwsdcDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});